services:
  api:
    build:
      context: . # Diretório raiz
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_URLS=http://*:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=github_repo_app_db;User Id=postgres;Password=postgres
    networks:
      - app-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: github_repo_app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
